import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Link the menu items to the sidebar
  learnSidebar: [
    'learn/intro',
    {
      type: 'category',
      label: 'Learn',
      collapsible: false,
      link: undefined,
      items: [
        'learn/intro',
        'learn/alkanes',
        'learn/metashrew',
        'learn/faq',
      ],
    },
  ],

  developersSidebar: [
    {
      type: 'category',
      label: 'Developer Quickstart',
      collapsible: false,
      link: undefined,
      items: [
        'developers/intro',
        'developers/quickstart',
        'developers/regtest',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guides',
      collapsible: false,
      link: undefined,
      items: [
        'developers/contracts-building',
        'developers/contracts-interaction',
        'developers/protorunes',
        'developers/rpc',
        'developers/alkanes-libraries',
        'developers/dapp-integration',
      ],
    },
  ],
  //developersSidebar: [{type: 'autogenerated', dirName: 'developers'}],
  // But you can create a sidebar manually

  // mainSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Learn',
  //     collapsible: false,
  //     link: undefined,
  //     items: [
  //       'learn/intro',
  //       'learn/alkanes',
  //       'learn/metashrew',
  //       'learn/faq',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Developer Guides',
  //     collapsible: false,
  //     link: undefined,
  //     items: [
  //       'developers/intro',
  //       'developers/quickstart',
  //       'developers/regtest',
  //       'developers/contracts-building',
  //       'developers/contracts-interaction',
  //       'developers/protorunes',
  //       'developers/rpc',
  //       'developers/alkanes-libraries',
  //       'developers/dapp-integration',
  //     ],
  //   },
  // ],

};

export default sidebars;
