import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Link the menu items to the sidebar
  learnSidebar: [
    'learn/intro',
    {
      type: 'category',
      label: 'Learn',
      items: [
        'learn/intro',
      ],
    },
  ],

  developersSidebar: [
    'developers/quickstart/intro',
    {
      type: 'category',
      label: 'Developers',
      items: [
        'developers/quickstart/intro',
      ],
    },
  ],
  //developersSidebar: [{type: 'autogenerated', dirName: 'developers'}],
  // But you can create a sidebar manually

  mainSidebar: [
    {
      type: 'category',
      label: 'Learn',
      items: [
        'learn/intro',
      ],
    },
    {
      type: 'category',
      label: 'Developer Quickstart',
      items: [
        'developers/quickstart/intro',
        'developers/quickstart/prereq', 
        'developers/quickstart/setup',
        'developers/quickstart/build',
        'developers/quickstart/deploy-regtest',
        'developers/quickstart/deploy-testnet',
      ],
    },
    {
      type: 'category',
      label: 'Developer Guides',
      items: [
        'developers/guides/intro',
      ],
    },
  ],

};

export default sidebars;
